/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import logicaNegocios.Arbitro;
import logicaNegocios.Localidad;

import main.ControladoraGlobal;

public class IArbitro extends javax.swing.JInternalFrame {

    JInternalFrame unJInternalFrame;
    ControladoraGlobal unaControladoraGlobal;
    Arbitro unArbitro = null;

    public IArbitro(ControladoraGlobal unaControladoraGlobal) {
        initComponents();
        this.unaControladoraGlobal = unaControladoraGlobal;
        setFrameIcon(new ImageIcon(getClass().getResource("../Iconos Nuevos/referee.png")));
        IMenuPrincipalInterface.centrar(this);
        SeInicio(unaControladoraGlobal);

        jButtonImprimir.setEnabled(false);
        jButtonEditar.setEnabled(false);

        camposLimpiar();

    }

    public IArbitro(ControladoraGlobal unaControladoraGlobal, JInternalFrame unJInternalFrame) {
        initComponents();
        this.unaControladoraGlobal = unaControladoraGlobal;
        this.unJInternalFrame = unJInternalFrame;
        setFrameIcon(new ImageIcon(getClass().getResource("../Iconos Nuevos/referee.png")));
        IMenuPrincipalInterface.centrar(this);
        SeInicio(unaControladoraGlobal);

        jButtonImprimir.setEnabled(false);
        jButtonEditar.setEnabled(false);

        camposLimpiar();

    }

    public IArbitro(ControladoraGlobal unaControladoraGlobal, JInternalFrame unJInternalFrame, Arbitro unArbitro) {
        initComponents();
        this.unJInternalFrame = unJInternalFrame;
        this.setTitle("Arbitro: " + unArbitro.getApellido() + " " + unArbitro.getNombre());
        SeInicio(unaControladoraGlobal);

        this.unArbitro = unArbitro;
        jButtonImprimir.setEnabled(true);
        jButtonEditar.setEnabled(true);

        camposCargar(unArbitro);

    }

    public void SeInicio(ControladoraGlobal unaControladoraGlobal) {
        this.unaControladoraGlobal = unaControladoraGlobal;

        //Icono de la ventana
        setFrameIcon(new ImageIcon(getClass().getResource("../Iconos Nuevos/referee.png")));

        cargarComboBoxLocalidades();
        IMenuPrincipalInterface.centrar(this);

        camposActivo(false);
    }

    public void camposCargar(Arbitro unArbitro) {
        jTextFieldDNI.setText(unArbitro.getDni().toString());
        jTextFieldApellido.setText(unArbitro.getApellido());
        jTextFieldNombres.setText(unArbitro.getNombre());
        jComboBoxLocalidad.setSelectedItem(unArbitro.getUnaLocalidad());
        jTextFieldDomicilio.setText(unArbitro.getDomicilio());
        jTextFieldEmail.setText(unArbitro.getEmail());

        DateFormat df = DateFormat.getDateInstance();
        jTextFieldFechaNacimiento.setText(df.format(unArbitro.getFechaNacimiento()));
        jTextFieldFechaIngreso.setText(df.format(unArbitro.getFechaIngreso()));

        jTextFieldTelFijo.setText(unArbitro.getTelFijo());
        jTextFieldTelCelular.setText(unArbitro.getTelCelular());

    }

    public void cargarComboBoxLocalidades() {
        DefaultComboBoxModel modelCombo = new DefaultComboBoxModel((Vector) unaControladoraGlobal.getLocalidadesBD());
        this.jComboBoxLocalidad.setModel(modelCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabelDni10 = new javax.swing.JLabel();
        jLabelApellido10 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelLocalidad10 = new javax.swing.JLabel();
        jComboBoxLocalidad10 = new javax.swing.JComboBox();
        jTextFieldNombres10 = new javax.swing.JTextField();
        jTextFieldApellido10 = new javax.swing.JTextField();
        jTextFieldDNI10 = new javax.swing.JTextField();
        jLabelDomicilio16 = new javax.swing.JLabel();
        jTextFieldDomicilio8 = new javax.swing.JTextField();
        jLabelFechaNacimiento8 = new javax.swing.JLabel();
        jLabelFechaIngreso24 = new javax.swing.JLabel();
        jTextFieldFechaNacimiento8 = new javax.swing.JTextField();
        jTextFieldFechaIngreso8 = new javax.swing.JTextField();
        jLabelFotocopiaDni = new javax.swing.JLabel();
        jTextFieldFotocopiaDni = new javax.swing.JTextField();
        jButtonExaminarFotocopia = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail8 = new javax.swing.JTextField();
        jLabelTelFijo = new javax.swing.JLabel();
        jTextFieldTelFijo8 = new javax.swing.JTextField();
        jLabelTelCelular = new javax.swing.JLabel();
        jTextFieldTelCelular8 = new javax.swing.JTextField();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos Nuevos/add2.png"))); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos Nuevos/printer.png"))); // NOI18N
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos Nuevos/save.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos Nuevos/cancel.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos Nuevos/Edit2.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(3, 3, 3))
        );

        jLabelDni10.setText("DNI");

        jLabelApellido10.setText("Apellido");

        jLabelNombre.setText("Nombres");

        jLabelLocalidad10.setText("Localidad");

        jTextFieldDNI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });

        jLabelDomicilio16.setText("Domicilio");

        jLabelFechaNacimiento8.setText("Fecha de Nacimiento");

        jLabelFechaIngreso24.setText("Fecha Ingreso");

        jTextFieldFechaNacimiento8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNacimientoActionPerformed(evt);
            }
        });

        jTextFieldFechaIngreso8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaIngresoActionPerformed(evt);
            }
        });

        jLabelFotocopiaDni.setText("Fotocopia de DNI");

        jButtonExaminarFotocopia.setText("...");

        jLabelEmail.setText("E-mail");

        jLabelTelFijo.setText("Telefono Fijo");

        jLabelTelCelular.setText("Telefono Celular");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaNacimiento8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFechaIngreso24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldFechaNacimiento8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldFechaIngreso8)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmail8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel13Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelLocalidad10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelDomicilio16, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel13Layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jTextFieldNombres10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBoxLocalidad10, 0, 160, Short.MAX_VALUE)
                                                .addComponent(jTextFieldDomicilio8)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(jLabelApellido10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldApellido10))
                                .addGroup(jPanel13Layout.createSequentialGroup()
                                    .addComponent(jLabelDni10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldDNI10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTelFijo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabelFotocopiaDni, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jTextFieldFotocopiaDni, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExaminarFotocopia, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jTextFieldTelCelular8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelFijo8, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(89, 89, 89))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDNI10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDni10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido10)
                    .addComponent(jTextFieldApellido10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombres10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxLocalidad10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocalidad10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDomicilio16)
                    .addComponent(jTextFieldDomicilio8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFechaNacimiento8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaNacimiento8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaIngreso24)
                    .addComponent(jTextFieldFechaIngreso8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelFijo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelFijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelCelular8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFotocopiaDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFotocopiaDni)
                    .addComponent(jButtonExaminarFotocopia))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        if (unJInternalFrame != null) {
            this.unJInternalFrame.setVisible(true);
        } else {
            IMenuPrincipalInterface.jDesktopPane.setVisible(true);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        camposActivo(true);
        camposLimpiar();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    public void camposActivo(boolean Editable) {
        jTextFieldDNI.setEditable(Editable);
        jTextFieldApellido.setEditable(Editable);
        jTextFieldNombres.setEditable(Editable);
        jComboBoxLocalidad.setEnabled(Editable);
        jTextFieldDomicilio.setEditable(Editable);
        jTextFieldEmail.setEditable(Editable);
        jTextFieldFechaNacimiento.setEditable(Editable);
        jTextFieldFechaIngreso.setEditable(Editable);
        jTextFieldTelFijo.setEditable(Editable);
        jTextFieldTelCelular.setEditable(Editable);
        jTextFieldFotocopiaDni.setEditable(Editable);

        jButtonGuardar.setEnabled(Editable);
        jButtonCancelar.setEnabled(Editable);
        jButtonNuevo.setEnabled(!Editable);
    }

    public void camposLimpiar() {
        jTextFieldDNI.setText("");
        jTextFieldApellido.setText("");
        jTextFieldNombres.setText("");
        jTextFieldDomicilio.setText("");
        jTextFieldEmail.setText("");
        jTextFieldFechaNacimiento.setText("");
        jTextFieldFechaIngreso.setText("");
        jTextFieldTelFijo.setText("");
        jTextFieldTelCelular.setText("");
        jTextFieldFotocopiaDni.setText("");
    }

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        DateFormat df = DateFormat.getDateInstance();
        try {
            Date fechaNacimiento = new java.sql.Date(df.parse(jTextFieldFechaNacimiento.getText()).getTime());
            Date fechaIngreso = new java.sql.Date(df.parse(jTextFieldFechaIngreso.getText()).getTime());

            unaControladoraGlobal.crearArbitro(Long.parseLong(jTextFieldDNI.getText()),
                    jTextFieldApellido.getText(),
                    jTextFieldNombres.getText(),
                    (Localidad) jComboBoxLocalidad.getSelectedItem(),
                    jTextFieldDomicilio.getText(),
                    fechaNacimiento,
                    fechaIngreso,
                    "FOTO CARNET",
                    jTextFieldEmail.getText(),
                    jTextFieldTelFijo.getText(),
                    jTextFieldTelCelular.getText());
            JOptionPane.showMessageDialog(this, "Arbitro Generado");
            camposActivo(false);
            camposLimpiar();

        } catch (ParseException e) {
            System.out.println("ERROR EN LAS FECHAS SOCIA" + e.getMessage());
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        if (this.unArbitro == null) {
            camposLimpiar();
        } else {
            camposCargar(unArbitro);
        }
        camposActivo(false);
        jButtonNuevo.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        camposActivo(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaIngresoActionPerformed

    private void jTextFieldFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNacimientoActionPerformed

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExaminarFotocopia;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JCheckBox jCheckBoxExJugadora;
    private javax.swing.JCheckBox jCheckBoxExJugadora1;
    private javax.swing.JCheckBox jCheckBoxExJugadora2;
    private javax.swing.JCheckBox jCheckBoxExJugadora3;
    private javax.swing.JCheckBox jCheckBoxExJugadora4;
    private javax.swing.JCheckBox jCheckBoxExJugadora5;
    private javax.swing.JCheckBox jCheckBoxExJugadora6;
    private javax.swing.JCheckBox jCheckBoxExJugadora7;
    private javax.swing.JComboBox jComboBoxLocalidad;
    private javax.swing.JComboBox jComboBoxLocalidad1;
    private javax.swing.JComboBox jComboBoxLocalidad10;
    private javax.swing.JComboBox jComboBoxLocalidad2;
    private javax.swing.JComboBox jComboBoxLocalidad3;
    private javax.swing.JComboBox jComboBoxLocalidad4;
    private javax.swing.JComboBox jComboBoxLocalidad5;
    private javax.swing.JComboBox jComboBoxLocalidad6;
    private javax.swing.JComboBox jComboBoxLocalidad7;
    private javax.swing.JComboBox jComboBoxLocalidad8;
    private javax.swing.JComboBox jComboBoxLocalidad9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido10;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelApellido3;
    private javax.swing.JLabel jLabelApellido4;
    private javax.swing.JLabel jLabelApellido5;
    private javax.swing.JLabel jLabelApellido6;
    private javax.swing.JLabel jLabelApellido7;
    private javax.swing.JLabel jLabelApellido8;
    private javax.swing.JLabel jLabelApellido9;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelDni1;
    private javax.swing.JLabel jLabelDni10;
    private javax.swing.JLabel jLabelDni2;
    private javax.swing.JLabel jLabelDni3;
    private javax.swing.JLabel jLabelDni4;
    private javax.swing.JLabel jLabelDni5;
    private javax.swing.JLabel jLabelDni6;
    private javax.swing.JLabel jLabelDni7;
    private javax.swing.JLabel jLabelDni8;
    private javax.swing.JLabel jLabelDni9;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelDomicilio1;
    private javax.swing.JLabel jLabelDomicilio10;
    private javax.swing.JLabel jLabelDomicilio11;
    private javax.swing.JLabel jLabelDomicilio12;
    private javax.swing.JLabel jLabelDomicilio13;
    private javax.swing.JLabel jLabelDomicilio14;
    private javax.swing.JLabel jLabelDomicilio15;
    private javax.swing.JLabel jLabelDomicilio16;
    private javax.swing.JLabel jLabelDomicilio2;
    private javax.swing.JLabel jLabelDomicilio3;
    private javax.swing.JLabel jLabelDomicilio4;
    private javax.swing.JLabel jLabelDomicilio5;
    private javax.swing.JLabel jLabelDomicilio6;
    private javax.swing.JLabel jLabelDomicilio7;
    private javax.swing.JLabel jLabelDomicilio8;
    private javax.swing.JLabel jLabelDomicilio9;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelExJugadora;
    private javax.swing.JLabel jLabelExJugadora1;
    private javax.swing.JLabel jLabelExJugadora2;
    private javax.swing.JLabel jLabelExJugadora3;
    private javax.swing.JLabel jLabelExJugadora4;
    private javax.swing.JLabel jLabelExJugadora5;
    private javax.swing.JLabel jLabelExJugadora6;
    private javax.swing.JLabel jLabelExJugadora7;
    private javax.swing.JLabel jLabelFechaIngreso;
    private javax.swing.JLabel jLabelFechaIngreso1;
    private javax.swing.JLabel jLabelFechaIngreso10;
    private javax.swing.JLabel jLabelFechaIngreso11;
    private javax.swing.JLabel jLabelFechaIngreso12;
    private javax.swing.JLabel jLabelFechaIngreso13;
    private javax.swing.JLabel jLabelFechaIngreso14;
    private javax.swing.JLabel jLabelFechaIngreso15;
    private javax.swing.JLabel jLabelFechaIngreso16;
    private javax.swing.JLabel jLabelFechaIngreso17;
    private javax.swing.JLabel jLabelFechaIngreso18;
    private javax.swing.JLabel jLabelFechaIngreso19;
    private javax.swing.JLabel jLabelFechaIngreso2;
    private javax.swing.JLabel jLabelFechaIngreso20;
    private javax.swing.JLabel jLabelFechaIngreso21;
    private javax.swing.JLabel jLabelFechaIngreso22;
    private javax.swing.JLabel jLabelFechaIngreso23;
    private javax.swing.JLabel jLabelFechaIngreso24;
    private javax.swing.JLabel jLabelFechaIngreso3;
    private javax.swing.JLabel jLabelFechaIngreso4;
    private javax.swing.JLabel jLabelFechaIngreso5;
    private javax.swing.JLabel jLabelFechaIngreso6;
    private javax.swing.JLabel jLabelFechaIngreso7;
    private javax.swing.JLabel jLabelFechaIngreso8;
    private javax.swing.JLabel jLabelFechaIngreso9;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelFechaNacimiento1;
    private javax.swing.JLabel jLabelFechaNacimiento2;
    private javax.swing.JLabel jLabelFechaNacimiento3;
    private javax.swing.JLabel jLabelFechaNacimiento4;
    private javax.swing.JLabel jLabelFechaNacimiento5;
    private javax.swing.JLabel jLabelFechaNacimiento6;
    private javax.swing.JLabel jLabelFechaNacimiento7;
    private javax.swing.JLabel jLabelFechaNacimiento8;
    private javax.swing.JLabel jLabelFotocopiaDni;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelLocalidad1;
    private javax.swing.JLabel jLabelLocalidad10;
    private javax.swing.JLabel jLabelLocalidad2;
    private javax.swing.JLabel jLabelLocalidad3;
    private javax.swing.JLabel jLabelLocalidad4;
    private javax.swing.JLabel jLabelLocalidad5;
    private javax.swing.JLabel jLabelLocalidad6;
    private javax.swing.JLabel jLabelLocalidad7;
    private javax.swing.JLabel jLabelLocalidad8;
    private javax.swing.JLabel jLabelLocalidad9;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelNombres1;
    private javax.swing.JLabel jLabelNombres2;
    private javax.swing.JLabel jLabelNombres3;
    private javax.swing.JLabel jLabelNombres4;
    private javax.swing.JLabel jLabelNombres5;
    private javax.swing.JLabel jLabelNombres6;
    private javax.swing.JLabel jLabelNombres7;
    private javax.swing.JLabel jLabelNombres8;
    private javax.swing.JLabel jLabelNombres9;
    private javax.swing.JLabel jLabelTelCelular;
    private javax.swing.JLabel jLabelTelFijo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido10;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldApellido3;
    private javax.swing.JTextField jTextFieldApellido4;
    private javax.swing.JTextField jTextFieldApellido5;
    private javax.swing.JTextField jTextFieldApellido6;
    private javax.swing.JTextField jTextFieldApellido7;
    private javax.swing.JTextField jTextFieldApellido8;
    private javax.swing.JTextField jTextFieldApellido9;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDNI1;
    private javax.swing.JTextField jTextFieldDNI10;
    private javax.swing.JTextField jTextFieldDNI2;
    private javax.swing.JTextField jTextFieldDNI3;
    private javax.swing.JTextField jTextFieldDNI4;
    private javax.swing.JTextField jTextFieldDNI5;
    private javax.swing.JTextField jTextFieldDNI6;
    private javax.swing.JTextField jTextFieldDNI7;
    private javax.swing.JTextField jTextFieldDNI8;
    private javax.swing.JTextField jTextFieldDNI9;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldDomicilio1;
    private javax.swing.JTextField jTextFieldDomicilio2;
    private javax.swing.JTextField jTextFieldDomicilio3;
    private javax.swing.JTextField jTextFieldDomicilio4;
    private javax.swing.JTextField jTextFieldDomicilio5;
    private javax.swing.JTextField jTextFieldDomicilio6;
    private javax.swing.JTextField jTextFieldDomicilio7;
    private javax.swing.JTextField jTextFieldDomicilio8;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldEmail2;
    private javax.swing.JTextField jTextFieldEmail3;
    private javax.swing.JTextField jTextFieldEmail4;
    private javax.swing.JTextField jTextFieldEmail5;
    private javax.swing.JTextField jTextFieldEmail6;
    private javax.swing.JTextField jTextFieldEmail7;
    private javax.swing.JTextField jTextFieldEmail8;
    private javax.swing.JTextField jTextFieldFechaIngreso;
    private javax.swing.JTextField jTextFieldFechaIngreso1;
    private javax.swing.JTextField jTextFieldFechaIngreso2;
    private javax.swing.JTextField jTextFieldFechaIngreso3;
    private javax.swing.JTextField jTextFieldFechaIngreso4;
    private javax.swing.JTextField jTextFieldFechaIngreso5;
    private javax.swing.JTextField jTextFieldFechaIngreso6;
    private javax.swing.JTextField jTextFieldFechaIngreso7;
    private javax.swing.JTextField jTextFieldFechaIngreso8;
    private javax.swing.JTextField jTextFieldFechaNacimiento;
    private javax.swing.JTextField jTextFieldFechaNacimiento1;
    private javax.swing.JTextField jTextFieldFechaNacimiento2;
    private javax.swing.JTextField jTextFieldFechaNacimiento3;
    private javax.swing.JTextField jTextFieldFechaNacimiento4;
    private javax.swing.JTextField jTextFieldFechaNacimiento5;
    private javax.swing.JTextField jTextFieldFechaNacimiento6;
    private javax.swing.JTextField jTextFieldFechaNacimiento7;
    private javax.swing.JTextField jTextFieldFechaNacimiento8;
    private javax.swing.JTextField jTextFieldFotocopiaDni;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextFieldNombres1;
    private javax.swing.JTextField jTextFieldNombres10;
    private javax.swing.JTextField jTextFieldNombres2;
    private javax.swing.JTextField jTextFieldNombres3;
    private javax.swing.JTextField jTextFieldNombres4;
    private javax.swing.JTextField jTextFieldNombres5;
    private javax.swing.JTextField jTextFieldNombres6;
    private javax.swing.JTextField jTextFieldNombres7;
    private javax.swing.JTextField jTextFieldNombres8;
    private javax.swing.JTextField jTextFieldNombres9;
    private javax.swing.JTextField jTextFieldTelCelular;
    private javax.swing.JTextField jTextFieldTelCelular1;
    private javax.swing.JTextField jTextFieldTelCelular2;
    private javax.swing.JTextField jTextFieldTelCelular3;
    private javax.swing.JTextField jTextFieldTelCelular4;
    private javax.swing.JTextField jTextFieldTelCelular5;
    private javax.swing.JTextField jTextFieldTelCelular6;
    private javax.swing.JTextField jTextFieldTelCelular7;
    private javax.swing.JTextField jTextFieldTelCelular8;
    private javax.swing.JTextField jTextFieldTelFijo;
    private javax.swing.JTextField jTextFieldTelFijo1;
    private javax.swing.JTextField jTextFieldTelFijo2;
    private javax.swing.JTextField jTextFieldTelFijo3;
    private javax.swing.JTextField jTextFieldTelFijo4;
    private javax.swing.JTextField jTextFieldTelFijo5;
    private javax.swing.JTextField jTextFieldTelFijo6;
    private javax.swing.JTextField jTextFieldTelFijo7;
    private javax.swing.JTextField jTextFieldTelFijo8;
    // End of variables declaration//GEN-END:variables
}
